version: '3'

services:
  api:
    depends_on:
      - postgres_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3335:3335
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres_container:5432/pos-tech-db?schema=public
    links:
      - postgres_container:postgres_container

  postgres_container:
    image: "postgres"
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pos-tech-db
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
