version: '3'

services:
  api:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password@postgres:5432/pos-tech-db?schema=public
    links:
      - postgres:postgres

  postgres:
    image: "postgres"
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pos-tech-db
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data

volumes:
  data: